config/routes.rb
Rails.application.routes.draw do
  get 'answers/reply' => 'answers#reply', as: 'reply'
  resources :answers
  root to: "questions#index"

  resources :questions
  devise_for :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user

  validates :body ,presence: true
  validates :title, presence: true

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history] 

  def should_generate_new_friendly_id?
    title_changed?
  end

  def author
  	self.user.name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  has_many :questions, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  def reply
    @answer = Answer.new

    @id = params[:id]
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to :back, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to :back, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content, :question_id, :parent_id, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :user_sign?, only: [:new, :create,:edit, :update]
  before_action :correct_user,   only: [:edit, :update,:destroy]



  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, :user_id)
    end

    def correct_user
      if @question.user_id != current_user.id
        flash[:danger] = 'Only author can change the Question'
        redirect_to(:back)
      end
    end 
    # check for user sign in
    def user_sign? 
      if current_user.nil?
        flash[:danger] = 'Please sign in'
        redirect_to( user_session_path)
      end
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  # get the child of the Question
  def parent_question(question_id)
    # get all the child answer of the articles
    answers = Answer.where('answers.question_id = ?', question_id)
    # get all child answer of parent answer
    answers.map  do |answer|
      # @answer instance for answer partial
      @answer = answer
      #get all the child answer of each parent answer
      child_answer(answer.id)
    end.join.html_safe
  end

  def child_answer(parent_id)
    answer_array = Answer.where('answers.parent_id = ?', parent_id)
    # if parent_answer has not child answer then return the answer
    if answer_array.empty?
      return render 'answers/answer'
    else
      # if parent_answer has child answer then get the child answer of parent answer
      k = (
      answer_array.map  do |answer|
        @answer = answer
        child_answer(answer.id)
      end
      ).join.html_safe
      # @answer instance variable for partial for answer 
      @answer = Answer.find(parent_id)
      # html of parent answer plus child answer enclose in the replies div tag
      k = (render 'answers/answer').html_safe + content_tag(:div,k, class: "replies").html_safe
      return (k)
    end
  end
end

app/views/answers/_answer.html.erb
<div class="well well-sm">
  <p class="text-muted">Answered by <strong><%= @answer.user.name %></strong> on
    <%= l(@answer.created_at, format: '%B, %d %Y %H:%M:%S') %></p>
    <p><%= @answer.content %></p>    
    <%if user_signed_in? %>
    <div class =<%="reply#{@answer.id}"%>>
      <div class= "row"> 
        <div class = "col-sm-1">     
          <button  class= "ajax btn btn-primary btn-sm" value = <%=@answer.id%> >Reply</button>
          <% if (current_user && @answer.user.id == current_user.id && Answer.where(parent_id: @answer.id).empty? ) %>
        </div>
        <div>
          <%= button_to "Delete", answer_path(@answer.id), :method => "delete",data: { confirm: "You sure?" }, :class =>"btn btn-danger btn-sm" %>
          <%end%>
        </div>
      </div>
    </div>
  <%end%>


</div>

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content,  cols: "60", rows: "4" %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/_reply.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :parent_id , :value =>@id %>
  </div>
  <div class="field">
    <%= f.label :Reply %><br>
    <%= f.text_area :content,  cols: "60", rows: "4" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Question</th>
      <th>Parent</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.content %></td>
        <td><%= answer.question_id %></td>
        <td><%= answer.parent_id %></td>
        <td><%= answer.user_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/reply.js.erb
$(".reply<%=@id%>").html("<%= j(render(:partial => "reply", :locals => { :f => @answer})) %>");

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @answer.parent_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum 3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Forum 3', root_path, class: 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/questions">Questions</a></li>
        </ul>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%= current_user.name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
               <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
               <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <% end %>
          </ul> 
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<div class = "container">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

        <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
      <%= f.label :body %><br>
      <%= f.text_area :body, rows: "8", cols:"64" %>

    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class= "row">
  <div class = "col-sm-10">
    <div class ="container">
      <h2>Questions</h2>
      <%@questions.each do |question|%>
        <div class="jumbotron" style = "word-wrap: break-word; size: 100x60 ;" >
          <h2><%=question.title%></h2>
           <p style = "font-family: 'Calibri','Slate Pro','sans-serif' !important; color:#262626; font-size: 16px!important "><%=truncate(question.body, length: 300,omission: '...(continued)' ).html_safe%></p>
          <p><strong><%=question.user.name%></strong></p>
        
          <a href = <%="/questions/#{question.slug}"%>><button type="button" class="btn btn-primary btn-sm">Read More</button></a>
        </div>
      <%end%>
    </div>
  </div>
  <div class = "col-sm-2">
    <a href = "/questions/new"><button type="button" class="btn btn-success">Create Question</button></a>
  </div>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class ="container">
  <div class="well" style = "word-wrap: break-word;">
    <h2><%=@question.title%></h2>
    <p ><%=raw @question.body.html_safe%></p>
    <h3><%=@question.author%></strong></h3>

    <div class= "row">
      <%if   current_user && @question.user_id == current_user.id%>
      <div class= "col-sm-1">
        <a href = "/questions/<%=@question.slug%>/edit"> <button type="button" class="btn btn-info btn-sm">Edit</button></a>
      </div>
      <div style = "width:20%">
           <%= button_to "Delete", question_path(@question.id), :method => "delete",data: { confirm: "You sure?" }, :class =>"btn btn-danger btn-sm" %>
        <%end%>
      </div>
    </div>
  </div>
  <%= parent_question(@question.id)%>
  <div>
    <% if user_signed_in? %>
      <% @answer = Answer.new%>
      <%= form_for(@answer) do |f| %>
        <% if @answer.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

            <ul>
            <% @answer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :answer %><br>
          <%= f.text_area :content,  cols: "60", rows: "5" %>
        </div>
        <div class="field">
          <%= f.hidden_field :question_id, :value => @question.id %>
        </div>

        <div class="field">
          <%= f.hidden_field :user_id, :value => current_user.id %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>

      <% end %>
        <% else%>
          <div class = "well">
          <p>You have to <a href = "/users/sign_in" style = "color: blue;"><strong>login</strong> </a> for post a question</p>
          </div>
    <% end %>
  </div>
</div>


<script>
$(document).ready(function(){
    $("button.ajax").click(function(){
  var id = $(this).val()
      $.ajax({
        type: "get",
        url: "<%= reply_path%>",
        data: {id: id}
      });
    });
});
</script>